version: '3'
services:
  redis-master-1:
    container_name: redis-master-1
    image: redis:6.2.3
    command: redis-server /etc/redis.conf
    volumes:
    - ./redis-master-1.conf:/etc/redis.conf
    restart: always
    ports:
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
      - 7006:7006

  redis-master-2:
    container_name: redis-master-2
    image: redis:6.2.3
    network_mode: "service:redis-master-1" 
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-master-2.conf:/etc/redis.conf

  redis-master-3:
    container_name: redis-master-3
    image: redis:6.2.3
    network_mode: "service:redis-master-1" 
    command: redis-server /etc/redis.conf
    volumes:
    - ./redis-master-3.conf:/etc/redis.conf

  redis-slave-1:
    container_name: redis-slave-1
    image: redis:6.2.3
    network_mode: "service:redis-master-1" 
    command: redis-server /etc/redis.conf
    volumes:
    - ./redis-slave-1.conf:/etc/redis.conf

  redis-slave-2:
    container_name: redis-slave-2
    image: redis:6.2.3
    network_mode: "service:redis-master-1" 
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-slave-2.conf:/etc/redis.conf

  redis-slave-3:
    container_name: redis-slave-3
    image: redis:6.2.3
    network_mode: "service:redis-master-1" 
    command: redis-server /etc/redis.conf
    volumes:
    - ./redis-slave-3.conf:/etc/redis.conf

  redis-cluster-entry:
    network_mode: "service:redis-master-1"
    image: redis:6.2.3
    container_name: redis-cluster
    command: redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 127.0.0.1:7006 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-master-1
      - redis-master-2
      - redis-master-3
      - redis-slave-1
      - redis-slave-2
      - redis-slave-3